---
- name: Rebuild tower inventory (Pause)
  pause:
    seconds: 30
    prompt: Wait for 30 seconds for update to finish

- name: Rebuild tower inventory (Delete)
  tower_inventory:
    tower_config_file: "{{ tower_config_file }}" #define as extra vars
    state: absent
    name: "{{ item.invname }}"
    organization: "{{ item.orgname }}"
  loop: "{{ list_inv }}"
  when: item.state =='present'

- name: Rebuild tower inventory (Add)
  tower_inventory:
    tower_config_file: "{{ tower_config_file }}" #define as extra vars
    state: present
    name: "{{ item.invname }}"
    organization: "{{ item.orgname }}"
  loop: "{{ list_inv }}"

- name: Rebuild tower inventory source (Add)
  tower_inventory_source:
    tower_config_file: "{{ tower_config_file }}" #define as extra vars
    state: "{{ item.state }}"
    name: "{{ item.invsrcname }}"
    description: "{{ item.description }}"
    inventory: "{{ item.invname }}"
    source: "{{ item.type }}"
    source_project: "{{ item.proj }}"
    source_path: "{{ item.path }}"
    update_on_launch: true
    update_cache_timeout: 86400
  when: item.state =='present'
  loop: "{{ list_invsrc }}"

- name: Update tower project (Sync)
  awx.awx.tower_project_update:
    tower_config_file: "{{ tower_config_file }}" #define as extra vars
    project: "{{ item.proj }}"
    wait: true
  when: item.state =='present'
  loop: "{{ list_invsrc }}"

- name: Update tower inventory source (Sync)
  awx.awx.tower_inventory_source_update:
    tower_config_file: "{{ tower_config_file }}" #define as extra vars
    name: "{{ item.invsrcname }}"
    inventory: "{{ item.invname }}"
  when: item.state =='present'
  loop: "{{ list_invsrc }}"